CREATE TABLE topicos(
    id BIGINT NOT NULL AUTO_INCREMENT,
    titulo VARCHAR(100) NOT NULL UNIQUE,
    mensaje VARCHAR(500) NOT NULL UNIQUE,
    fecha DATETIME NOT NULL,
    curso VARCHAR(100) NOT NULL,

    PRIMARY KEY (id)
);